version: '3.9'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - logs:/usr/src/app/logs
    networks:
      - custom
  postgres:
    build: ./database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - custom
networks:
  custom:
    name: custom
    driver: bridge
volumes:
  logs:
  db: