version: '3.9'
services:
  postgres:
    build: ./database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - custom
networks:
  custom:
    name: custom
    driver: bridge
volumes:
  logs:
  db: